"""added id to resturantpizza2

Revision ID: 973ad8642651
Revises: 
Create Date: 2024-01-21 13:19:52.936095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973ad8642651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredients', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resturants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resturant_pizza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resturant_id', sa.Integer(), nullable=True),
    sa.Column('pizza_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.ForeignKeyConstraint(['resturant_id'], ['resturants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resturant_pizza')
    op.drop_table('resturants')
    op.drop_table('pizzas')
    # ### end Alembic commands ###
